version: '3.7'

services:
    nginx:
        image: nginx:1.17.4
        container_name: pizza_nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./docker_settings/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker_settings/logs:/var/log/nginx
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    image-nginx:
        image: nginx:1.17.4
        container_name: pizza_image_nginx
        restart: unless-stopped
        ports:
            - 8090:80
        volumes:
            - ./docker_settings/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker_settings/logs-image:/var/log/nginx
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: ./docker_settings
            dockerfile: Dockerfile_php82
        container_name: pizza_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker_settings/php.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
        depends_on:
            - mysql82
        networks:
            - app-network

    mysql82:
        build:
            context: ./docker_settings
            dockerfile: ./Dockerfile_mysql82
        container_name: pizza_mysql82
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Budapest
            LANG: C.UTF_8
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
            - "33064:3306"
        volumes:
            - ./docker_settings/mysql82_data:/var/lib/mysql
        user: ${CURRENT_UID:-}
        networks:
            - app-network

    mysql_test:
        image: mysql:8.0
        container_name: pizza_mysql_test
        environment:
            MYSQL_ROOT_PASSWORD: test_root
            MYSQL_DATABASE: test_database
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_password
            TZ: Europe/Budapest
            LANG: C.UTF_8
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
            - "33065:3306"
        volumes:
            - ./docker_settings/mysql_test_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: pizza_phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql82
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 1000M
        depends_on:
            - mysql82
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: docker_settings/Dockerfile_node
        container_name: pizza_node
        volumes:
            - './:/www/local'
        restart: always
        ports:
            - 8085:8080
        working_dir: /www/local
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        restart: unless-stopped
        container_name: pizza_mailhog
        volumes:
            - ./docker_settings/mailhog_data:/maildir
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /maildir
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

    selenium:
        image: selenium/standalone-chrome:latest
        container_name: pizza_selenium
        ports:
            - "4444:4444"
        networks:
            - app-network

    minio:
        image: minio/minio
        container_name: pizza-minio
        volumes:
            - ./docker_settings/s3-minio:/data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        command: server --console-address :9001 /data
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 1m30s
            timeout: 20s
            retries: 3
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
    web:
        external: true

volumes:
    mysql_data:
        driver: local
